/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Dog } from "./types";

export const DEFAULT_ADMIN_PW = "admin123";
export const ADMIN_PHONE = "5492346306562";
export const DONATION_LINK = "https://cafecito.app/refugiocasa";
export const ANNOUNCEMENT = "🐾 ¡Bienvenidos al Registro de Mascotas de Capilla del Señor! Registrá a tu mascota para que siempre esté identificada.";
export const LS_ANNOUNCEMENT = "registro-mascotas-announcement";
export const LS_KEY = "registro-mascotas-dogs";
export const LS_DARK = "registro-mascotas-dark";
export const LS_USER = "registro-mascotas-user";

export const SAMPLE_DOGS: Dog[] = [
  {
    id: "s01",
    name: "Rocky",
    breed: "Labrador",
    color: "Dorado",
    size: "Grande",
    sex: "Macho",
    neutered: "Sí",
    ownerName: "Martín López",
    ownerPhone: "+5492346301111",
    neighborhood: "Centro",
    notes: "Muy amigable.",
    photo: null,
    type: "owned",
    hasCollar: "Sí",
    collarColor: "Azul",
    lostSince: new Date(Date.now() - 3 * 3600000).toISOString(),
    lastSeenLocation: "Plaza San Martín, Centro",
    sightings: [
      { id: "si1", text: "Lo vi corriendo por la plaza", location: "Plaza San Martín", date: new Date(Date.now() - 2 * 3600000).toISOString() },
      { id: "si2", text: "Echado en la vereda de la panadería", location: "Av. Mitre 450", date: new Date(Date.now() - 1 * 3600000).toISOString() }
    ],
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString()
  },
  {
    id: "s02",
    name: "Luna",
    breed: "Caniche",
    color: "Blanco",
    size: "Pequeño",
    sex: "Hembra",
    neutered: "Sí",
    ownerName: "Carolina Ruiz",
    ownerPhone: "+5492346302222",
    neighborhood: "Barrio Norte",
    notes: "Moñito rosa y chip. Muy miedosa.",
    photo: null,
    type: "owned",
    hasCollar: "Sí",
    collarColor: "Rosa",
    lostSince: new Date(Date.now() - 18 * 3600000).toISOString(),
    lastSeenLocation: "Belgrano y Sarmiento",
    sightings: [],
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString()
  },
  {
    id: "s03",
    name: "Toto",
    breed: "Mestizo",
    color: "Marrón y negro",
    size: "Mediano",
    sex: "Macho",
    neutered: "Sí",
    ownerName: "Pablo García",
    ownerPhone: "+5492346303333",
    neighborhood: "Las Quintas",
    notes: "Mancha blanca en el pecho.",
    photo: null,
    type: "owned",
    hasCollar: "No",
    collarColor: "",
    lostSince: null,
    lastSeenLocation: null,
    sightings: [],
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString()
  },
  {
    id: "s04",
    name: "Mora",
    breed: "Pastor Alemán",
    color: "Negro y fuego",
    size: "Grande",
    sex: "Hembra",
    neutered: "Sí",
    ownerName: "Lucía Fernández",
    ownerPhone: "+5492346304444",
    neighborhood: "Villa del Parque",
    notes: "Responde a silbidos. Tiene chip.",
    photo: null,
    type: "owned",
    hasCollar: "Sí",
    collarColor: "Rojo",
    lostSince: null,
    lastSeenLocation: null,
    sightings: [],
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString()
  },
  {
    id: "s05",
    name: "Manchas",
    breed: "Mestizo",
    color: "Blanco con manchas negras",
    size: "Mediano",
    sex: "Macho",
    neutered: "Sí",
    ownerName: "—",
    ownerPhone: "",
    neighborhood: "Estación",
    notes: "Se lo ve por la estación. Manso, se deja acariciar.",
    photo: null,
    type: "stray",
    adoptionStatus: "transit",
    lostSince: null,
    lastSeenLocation: "Estación de tren",
    sightings: [],
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString()
  },
  {
    id: "s06",
    name: "Canela",
    breed: "Mestiza",
    color: "Marrón claro",
    size: "Pequeño",
    sex: "Hembra",
    neutered: "No",
    ownerName: "—",
    ownerPhone: "",
    neighborhood: "Ruta 8",
    notes: "Encontrada atropellada, se recuperó. Necesita hogar urgente.",
    photo: null,
    type: "stray",
    adoptionStatus: "urgent",
    lostSince: null,
    lastSeenLocation: null,
    sightings: [],
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString()
  },
  {
    id: "s07",
    name: "Negro",
    breed: "Labrador mix",
    color: "Negro",
    size: "Grande",
    sex: "Macho",
    neutered: "Sí",
    ownerName: "—",
    ownerPhone: "",
    neighborhood: "Centro",
    notes: "Muy tranquilo, ideal para familia con chicos.",
    photo: null,
    type: "stray",
    adoptionStatus: "shelter",
    lostSince: null,
    lastSeenLocation: null,
    sightings: [],
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString()
  },
  {
    id: "s08",
    name: "Princesa",
    breed: "Cocker Spaniel",
    color: "Dorado",
    size: "Mediano",
    sex: "Hembra",
    neutered: "Sí",
    ownerName: "—",
    ownerPhone: "",
    neighborhood: "Centro",
    notes: "Rescatada de situación de abandono. Cariñosa y juguetona.",
    photo: null,
    type: "stray",
    adoptionStatus: "shelter",
    lostSince: null,
    lastSeenLocation: null,
    sightings: [],
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString()
  },
  {
    id: "s09",
    name: "Pirata",
    breed: "Mestizo",
    color: "Blanco y marrón",
    size: "Mediano",
    sex: "Macho",
    neutered: "No",
    ownerName: "—",
    ownerPhone: "",
    neighborhood: "Centro",
    notes: "Un ojo celeste, otro marrón. Súper sociable con otros perros.",
    photo: null,
    type: "stray",
    adoptionStatus: "shelter",
    lostSince: null,
    lastSeenLocation: null,
    sightings: [],
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString()
  },
  {
    id: "s10",
    name: "Coco",
    breed: "Salchicha mix",
    color: "Negro y fuego",
    size: "Pequeño",
    sex: "Macho",
    neutered: "Sí",
    ownerName: "—",
    ownerPhone: "",
    neighborhood: "Ruta 8",
    notes: "Encontrado en la ruta. Ya vacunado y desparasitado. Urgente, necesita espacio.",
    photo: null,
    type: "stray",
    adoptionStatus: "urgent",
    lostSince: null,
    lastSeenLocation: null,
    sightings: [],
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString()
  },
];
